### ISSUE TITLE
Update Token Symbol Icon

### ISSUE THREAD

**Issue by sonyyang49** [iost-official/iost-extension#13]
Hi can you update our Token symbol icon?  

Token name:  otbc
Website:  https://www.otbtrade.com 

We are the new IOST DEX.  I attached to symbol img.  

![otbc](https://user-images.githubusercontent.com/42680294/76333483-b600c200-62bf-11ea-824e-85c0b66645af.png)

**Comment by cbdev01** [comment]
done
