### ISSUE TITLE
Long Term Feature request: local dev net support

### ISSUE THREAD

**Issue by lispc** [iost-official/iost-extension#15]
Currently this extension only supports testnet and mainnet. Some developers may not like others to view their contracts before they release their product. So if this extension can support local dev net, it will be quite helpful

**Comment by zakionigiri** [comment]
@lispc 
I have issued [a pull request](https://github.com/iost-official/iost-extension/pull/20) for this feature. 
Please check that up.

**Comment by lispc** [comment]
Great job！we will check it

**Comment by cbdev01** [comment]
done
